# @package _global_

model:
  model:
    e_layers: 2 
    d_model: 512
    d_ff: 32
    dropout: 0.047
    n_heads: 8
    patch_len: 10 
    stride: 2 

  pl_model:
    learning_rate: 0.00005