# @package _global_

model:
  model:
    e_layers: 2 
    d_model: 64
    d_ff: 512
    dropout: 0.038
    n_heads: 8
    patch_len: 7 
    stride: 2 

  pl_model:
    learning_rate: 0.0001