# @package _global_

model:
  model:
    e_layers: 3 
    d_model: 256
    d_ff: 256
    dropout: 0.059
    n_heads: 8
    patch_len: 10 
    stride: 8

  pl_model:
    learning_rate: 0.00006