# @package _global_

look_back_window: 48

model:
  model:
    e_layers: 4
    d_model: 32
    d_ff: 256
    dropout: 0.0801
    n_heads: 4
    patch_len: 15 
    stride: 3

  pl_model:
    learning_rate: 0.0003