# @package _global_

look_back_window: 60

model:
  model:
    e_layers: 2
    d_model: 64
    d_ff: 128
    dropout: 0.041
    n_heads: 4
    patch_len: 11 
    stride: 6

  pl_model:
    learning_rate: 0.0001