# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4643
    dropout_prob_theta: 0.0222
    kernel_size: 2
    n_hidden: 50
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.0046
    weight_decay: 0.001
