# @package _global_


model:
  pl_model:
    learning_rate: 0.001
    weight_decay: 0.00014
  model:
    stack_types: ["identity","exogenous_wavenet"]
    
    n_hidden: 250
    kernel_size: 3

    dropout_prob_theta: 0.0277
    dropout_prob_exogenous: 0.0438