# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.1147
    dropout_prob_theta: 0.0543
    kernel_size: 3
    n_hidden: 500
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.0011
    weight_decay: 0.0
