# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.1619
    dropout_prob_theta: 0.3668
    kernel_size: 4
    n_hidden: 500
    stack_types:
    - exogenous_tcn
    - identity
  pl_model:
    learning_rate: 0.0009
    weight_decay: 0.0
