# @package _global_

look_back_window: 14

model:
  pl_model:
    learning_rate: 0.0007
    weight_decay: 0.0001
  model:
    stack_types: ["identity", "exogenous_wavenet"]
    
    n_hidden: 455
    kernel_size: 5

    dropout_prob_theta: 0.209
    dropout_prob_exogenous: 0.07