# @package hydra.launcher
# always use the same GPU for doing the efficiency runs!
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 240 # 60min * 4 = 4h 
cpus_per_task: 1
mem_per_cpu: 4G
name: ${dataset.name}_${model.name}_${look_back_window}_${prediction_window}_${experiment}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
setup:
  - module load eth_proxy
additional_parameters:
  gpus: "rtx_2080:1"