# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 240 # 60min * 4 = 4h 
cpus_per_task: 1
gpus_per_node: 1
mem_per_cpu: 24G
gres: "gpumem:24g"
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
setup:
  - module load eth_proxy
srun_args:
  - "--gres=gpumem:24g"
additional_parameters:
  gres: "gpumem:24g"