
# @package _global_

model:
  model:
    e_layers: 1
    d_model: 64
    d_ff: 256
    dropout: 0.008
    n_heads: 16
    patch_len: 4 
    stride: 3 

  pl_model:
    learning_rate: 0.0005