# @package _global_

look_back_window: 5

model:
  model:
    e_layers: 2 
    d_model: 128
    d_ff: 256
    dropout: 0.184 
    n_heads: 16
    patch_len: 4 
    stride: 1 

  pl_model:
    learning_rate: 0.0018