# @package _global_


model:
  pl_model:
    learning_rate: 0.004
    weight_decay: 0.00002
  model:
    stack_types: [ "identity", "exogenous_wavenet"]
    
    n_hidden: 250
    kernel_size: 5

    dropout_prob_theta: 0.075
    dropout_prob_exogenous: 0.408