# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.2455
    dropout_prob_theta: 0.281
    kernel_size: 4
    n_hidden: 500
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.0068
    weight_decay: 0.0001
