# @package _global_


model:
  pl_model:
    learning_rate: 0.006
    weight_decay: 0.00726
  model:
    stack_types: ["exogenous_wavenet", "identity"]
    
    n_hidden: 250
    kernel_size: 3

    dropout_prob_theta: 0.305
    dropout_prob_exogenous: 0.326