# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.0267
    dropout_prob_theta: 0.2728
    kernel_size: 4
    n_hidden: 50
    stack_types:
    - identity
    - exogenous_tcn
  pl_model:
    learning_rate: 0.0013
    weight_decay: 0.0066
