# @package _global_


model:
  pl_model:
    learning_rate: 0.0012
    weight_decay: 0.00106
  model:
    stack_types: ["exogenous_tcn", "identity"]
    
    n_hidden: 500
    kernel_size: 3 

    dropout_prob_theta: 0.213
    dropout_prob_exogenous: 0.101