# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.0292
    dropout_prob_theta: 0.3073
    kernel_size: 5
    n_hidden: 500
    stack_types:
    - identity
    - exogenous_tcn
  pl_model:
    learning_rate: 0.0011
    weight_decay: 0.0031
