# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.045
    dropout_prob_theta: 0.1884
    kernel_size: 3
    n_hidden: 500
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.0008
    weight_decay: 0.0006
