# @package _global_

look_back_window: 28

model:
  pl_model:
    learning_rate: 0.001
    weight_decay: 0.00003
  model:
    stack_types: ["exogenous_wavenet", "identity"]
    
    n_hidden: 419
    kernel_size: 3

    dropout_prob_theta: 0.331
    dropout_prob_exogenous: 0.433