# @package _global_

look_back_window: 5

model:
  model:
    dropout_prob_exogenous: 0.2839
    dropout_prob_theta: 0.0009
    kernel_size: 2
    n_hidden: 250
    stack_types:
    - exogenous_tcn
    - identity
  pl_model:
    learning_rate: 0.0007
    weight_decay: 0.0
