# @package _global_

look_back_window: 20

model:
  model:
    d_model: 64 # 256
    d_ff: 64
    dropout: 0.1 # 0.254
    geomattn_dropout: 0.1 # 0.266
  pl_model:
    learning_rate: 0.001 # 0.0066
