dalia:
  "5":
    n_iter: 150
    n_states: 2
    transition_matrix_stickiness: 5.0
  "10":
    n_iter: 150
    n_states: 2
    transition_matrix_stickiness: 20.0
  "20":
    n_iter: 100
    n_states: 2
    transition_matrix_stickiness: 0.0
  "30":
    n_iter: 100
    n_states: 2
    transition_matrix_stickiness: 20.0
  "60":
    n_iter: 200
    n_states: 2
    transition_matrix_stickiness: 20.0
