dalia:
  "5": 
    n_points: 200
    learning_rate: 0.001
    num_latents: 6
    kernel: "rq"
    use_linear: 1
  "10": 
    n_points: 400
    learning_rate: 0.0005
    num_latents: 10
    kernel: "rq"
    use_linear: 1
  "20": 
    n_points: 400
    learning_rate: 0.0003
    num_latents: 9
    kernel: "rq"
    use_linear: 1
  "30": # not tuned, just take reasonable parameters 
    n_points: 2000
    learning_rate: 0.001
    num_latents: 8
    kernel: "matern"
    use_linear: 1
  "60": # not tuned, just take reasonable parameters 
    n_points: 2000
    learning_rate: 0.001
    num_latents: 8
    kernel: "matern"
    use_linear: 1
