"dalia":
  '5':
    learning_rate: 0.001
    weight_decay: 0.018
  '10':
    learning_rate: 0.002
    weight_decay: 0.006
  '20':
    learning_rate: 0.009
    weight_decay: 0.000
  '30':
    learning_rate: 0.003
    weight_decay: 0.0495
  '60':
    learning_rate: 0.0004
    weight_decay: 0.000