dalia:
  "5":
    model.pl_model.learning_rate: 0.002
    model.model.hid_dim: 64 
    model.model.n_hid_layers: 2
    model.model.dropout: 0.015
  "10":
    model.pl_model.learning_rate: 0.001
    model.model.hid_dim: 32
    model.model.n_hid_layers: 1
    model.model.dropout: 0.175
  "20":
    model.pl_model.learning_rate: 0.0005
    model.model.hid_dim: 512
    model.model.n_hid_layers: 3
    model.model.dropout: 0.148
  "30":
    model.pl_model.learning_rate: 0.001
    model.model.hid_dim: 256
    model.model.n_hid_layers: 3
    model.model.dropout: 0.023
  "60":
    model.pl_model.learning_rate: 0.002
    model.model.hid_dim: 32
    model.model.n_hid_layers: 2
    model.model.dropout: 0.032