dalia:
  "True":
    "5":
      "3":
        learning_rate: 0.002428582457141732
        tmax: 10
        patch_size: 4 
        d_model: 128

    "10":
      "3":
          learning_rate: 0.000492697225008562
          tmax: 20
          patch_size: 4
          d_model: 256
    
    "20":
      "3":
          learning_rate: 0.0008307336694718454
          tmax: 50
          patch_size: 4
          d_model: 256
    
    "30":
      "3":
          learning_rate: 0.001481167767662953
          tmax: 10
          patch_size: 4 
          d_model: 256
    
    "60":
      "3":
          learning_rate: 0.006663713645681199
          tmax: 20
          patch_size: 8
          d_model: 128
  "False":
    "5":
      "3":
        learning_rate: 0.00030107377696841794
        tmax: 50
        patch_size: 4 
        d_model: 256
    "10":
      "3":
        learning_rate: 0.0002539301902198614
        tmax: 50
        patch_size: 8
        d_model: 512
    "20":
      "3":
        learning_rate: 0.002428582457141732
        tmax: 10
        patch_size: 4
        d_model: 128
    "30":
      "3":
        learning_rate: 0.001041076216419349
        tmax: 10
        patch_size: 4
        d_model: 128
    "60":
      "3":
        learning_rate: 0.0003986785425517216
        tmax: 50
        patch_size: 8
        d_model: 512

