

dalia:
  "5":
    learning_rate: 0.01
    d_model: 256
    d_ff: 32
    dropout: 0.053
    geomattn_dropout: 0.155
  "10":
    learning_rate: 0.005
    d_model: 64
    d_ff: 512
    dropout: 0.042
    geomattn_dropout: 0.174
  "20":
    learning_rate: 0.003
    d_model: 64
    d_ff: 512
    dropout: 0.036
    geomattn_dropout: 0.235
  "30":
    learning_rate: 0.007
    d_model: 256
    d_ff: 64
    dropout: 0.004
    geomattn_dropout: 0.416
  "60":
    learning_rate: 0.002
    d_model: 256
    d_ff: 256
    dropout: 0.087
    geomattn_dropout: 0.409
 