

"dalia":
  "5":
      n_estimators: 684
      learning_rate: 0.026
      max_depth: 8
      reg_alpha: 0.076
      reg_lambda: 0.003
      subsample: 0.705
      colsample_bytree: 0.926
  "10":
      n_estimators: 325
      learning_rate: 0.030
      max_depth: 8
      reg_alpha: 0.333
      reg_lambda: 0.003
      subsample: 0.718
      colsample_bytree: 0.939
  "20":
      n_estimators: 896
      learning_rate: 0.008
      max_depth: 7
      reg_alpha: 0.000
      reg_lambda: 0.001
      subsample: 0.782
      colsample_bytree: 0.980
  "30":
      n_estimators: 401
      learning_rate: 0.0289
      max_depth: 8
      reg_alpha: 0.059
      reg_lambda: 0.000
      subsample: 0.828
      colsample_bytree: 0.958
  "60":
      n_estimators: 638
      learning_rate: 0.081
      max_depth: 6
      reg_alpha: 0.396
      reg_lambda: 0.018
      subsample: 0.745
      colsample_bytree: 0.941
  