
name: "adamshyper"

model:
  _target_: src.models.adamshyper.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  k: 1
  CSCM: 'Bottleneck_Construct'
  window_size: ${compute_square_window:${look_back_window}}  # window_size: [4,4] does not work if look_back_window < 4
  individual: False # False: Use Channel Dependence True: use channel independence
  channels: ${dataset.datamodule.look_back_channel_dim}

  # tunable params
  hyper_num: [50, 20, 10] 
  inner_size: 16
  d_model: 768 

  use_norm: ${use_norm_dl}

pl_model: 
  _target_: src.models.adamshyper.AdaMSHyper
  learning_rate: 0.002 
  loss: ${loss_fn}
  lradj: 'type1' # adjust learning rate
  use_amp: False

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 5

data:
  batch_size: 32
  num_workers: ${num_workers}

