
name: "adamshyper"

model:
  _target_: src.models.adamshyper.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  channels: ${dataset.datamodule.look_back_channel_dim} 
  d_model: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.d_model} 
  individual: False
  hyper_num: [50, 20, 10]
  inner_size: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.inner_size} 
  # window_size: [4,4] does not work if look_back_window < 4
  window_size: ${compute_square_window:${look_back_window}}
  CSCM: 'Bottleneck_Construct'
  k: 1

pl_model: 
  _target_: src.models.adamshyper.AdaMSHyper
  learning_rate: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.learning_rate} 
  # itr: 1 
  loss: 'MSE'
  lradj: 'type1' # adjust learning rate
  use_amp: False

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 5

data:
  batch_size: 256
  num_workers: ${num_workers}

