
name: "adamshyper"

model:
  _target_: src.models.adamshyper.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  CSCM: 'Bottleneck_Construct'
  channels: ${dataset.datamodule.look_back_channel_dim}
  individual: False # False: Use Channel Dependence True: use channel independence
  inner_size: 5 # afaik doesn't do anyhting
  window_size: ${compute_square_window:${look_back_window}}  # window_size: [4,4] does not work if look_back_window < 4

  # tunable params
  d_model: 512
  hn1: 50 # 50 # number of hyperedges at scale 1
  hn2: 20 # number of hyperedges at scale 2
  hn3: 10 # number of hyperedges at scale 3
  k: 3 # this is the eta parameter in the paper is used in the TOPK function to only take the top k in abs value edges per node and remove the other edges
  beta: 0.5
  gamma: 4.2

  use_norm: ${use_norm_dl}

pl_model: 
  _target_: src.models.adamshyper.AdaMSHyper
  learning_rate: 0.002 
  loss: ${loss_fn}
  lradj: 'type1' # adjust learning rate
  use_amp: False

trainer:
  max_epochs: 20
  use_early_stopping: True
  patience: 5

  gpu_mem: 24 
  n_gpus: 1

data:
  batch_size: 256 # 32
  num_workers: ${num_workers}

