
pl_model:
  name: ${model.name}
  n_trials: ${n_trials}
  normalization: ${normalization}
  local_norm: ${local_norm}
  local_norm_endo_only: ${local_norm_endo_only} 
  tune: ${tune}
  probabilistic_models: ${probabilistic_models} 
  seed: ${seed}