name: "bnn"

model: 
  _target_: src.models.bnn.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.datamodule.target_channel_dim}
  input_channels: ${dataset.datamodule.look_back_channel_dim}
  hid_dim: 16
  n_hid_layers: 4
  prior_scale: 8.0
  activation: "relu"
  heteroscedastic: False # if true, learn output noise
  output_noise_sigma: 0.001

pl_model: 
  _target_: src.models.bnn.BayesianNeuralNetwork
  learning_rate: 0.009
  num_samples: 25

trainer:
  max_epochs: 5
  use_early_stopping: False 
  patience: 3

data:
  batch_size: 256
