name: "dklgp"
n_points: 1000 # number of inducing points
strategy: "kmeans" # find inducing points using "kmeans" or "random" randomly sample inducing points

model:
  _target_: src.models.gp.GPModel
  num_latents: 1 
  num_tasks: ${prediction_window}

pl_model: 
  _target_: src.models.gp.GaussianProcess
  learning_rate: 0.001

trainer:
  use_early_stopping: True
  max_epochs: 10
  patience: 2

data: 
  batch_size: 256