name: "dropoutbnn"

model: 
  _target_: src.models.mlp.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.datamodule.target_channel_dim}
  input_channels: ${dataset.datamodule.look_back_channel_dim}
  hid_dim: 10
  n_hid_layers: 2
  activation: "relu" # can be tanh, relu or none
  dropout: 0.4

pl_model: 
  _target_: src.models.bnn.DropoutBNN
  learning_rate: 0.01
  loss: "MSE"
  num_samples: 50

trainer:
  max_epochs: 50
  use_early_stopping: False 

data:
  batch_size: 32
