name: "dummy"

model: 
  _target_: src.models.dummy.Model
  prediction_window: ${prediction_window}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

pl_model: 
  _target_: src.models.dummy.Dummy

trainer:
  max_epochs: 0
  use_early_stopping: False
  patience: 0 

data:
  batch_size: 256
