name: "dynamax"

model:
  _target_: src.models.dynamax.Dummy # dummy model we use hmmlearn

pl_model: 
  _target_: src.models.dynamax.DynamaxLightningModule
  n_states: 64
  n_iter: 100
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

trainer:
  max_epochs: 1
  use_early_stopping: False
  patience: 5

data: 
  batch_size: 256