name: "dynamax"

model:
  _target_: src.models.hmm.dynamax.HMM # dummy model we use hmmlearn

pl_model: 
  _target_: src.models.hmm.dynamax.HMMLightningModule
  n_states: 64
  n_iter: 100

trainer:
  max_epochs: 1
  use_early_stopping: False
  patience: 5

data: 
  batch_size: 256