defaults:
  - base_module

name: "ensemble"
ensemble_models: ["linear", "xgboost", "mlp", "mole"] # ["linear", "kalmanfilter", "mole", "xgboost", "gp", "mlp"]

model:
  _target_: src.models.ensemble.Model
  hidden_dim: 16
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim}
  freeze_experts: True
  softmax_temp: 1.0

  strategy: "mixture_net"

pl_model: 
  _target_: src.models.ensemble.Ensemble
  learning_rate: 0.001 

trainer:
  base_max_epochs: 1000
  max_epochs: ${ensemble_epochs:${model.model.strategy},${model.trainer.base_max_epochs}}
  use_early_stopping: True
  patience: 5

data: 
  batch_size: 256