name: "exactgp"

model:
  _target_: src.models.exactgp.ExactGPModel
  num_tasks: ${eval:${prediction_window} * ${dataset.datamodule.target_channel_dim}} # length of the output vector
  kernel: "rbf"  # can be "rbf", "matern", "rq" or "sm" spectral mixutre kernel
  periodic_type: "" # can be "additive", "multiplicative" or "" for no periodic kernel
  use_linear_trend: 1 # flag for using additive linear kernel

pl_model: 
  _target_: src.models.exactgp.ExactGaussianProcess
  learning_rate: 0.0011634474722097472

trainer:
  use_early_stopping: False
  max_epochs: 10
  patience: 2

data: 
  batch_size: 256