name: "exactgp"

model:
  _target_: src.models.exactgp.MultitaskGPModel
  num_tasks: ${prediction_window}
  kernel: "rq"
  periodic_type: "" 
  use_linear_trend: 1 

pl_model: 
  _target_: src.models.exactgp.ExactGP
  learning_rate: 0.0001
  use_norm: ${use_norm_baseline}

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 5

  gpu_mem: 4 
  n_gpus: 1

data: 
  batch_size: 256