name: "gp"
n_points: 2000 # number of inducing points
strategy: "kmeans" # find inducing points using "kmeans" or "random" randomly sample inducing points

model:
  _target_: src.models.gp.GPModel
  num_latents: 5 
  num_tasks: ${prediction_window}
  kernel: "rbf"  # can be "rbf", "matern", "rq" or "sm" spectral mixutre kernel
  periodic_type: "" # can be "additive", "multiplicative" or "" for no periodic kernel
  use_linear_trend: 1

pl_model: 
  _target_: src.models.gp.GaussianProcess
  learning_rate: 0.0011634474722097472

trainer:
  use_early_stopping: True
  max_epochs: 10
  patience: 2

data: 
  batch_size: 256