name: "gp"
n_points: ${params.gp.n_points} 
strategy: "kmeans" # find inducing points using "kmeans" or "random" randomly sample inducing points

model:
  _target_: src.models.gp.Model
  
  use_feature_extractor: ${model.pl_model.use_feature_extractor}
  
  # GP layer
  num_latents: ${params.gp.num_latents}
  num_tasks: ${prediction_window}
  kernel: ${params.gp.kernel} 
  periodic_type: ${params.gp.periodic_type}
  use_linear_trend: ${params.gp.use_linear_trend} 

  #Feature Extractor
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim}
  hidden_dim: 8
  out_dim: 16
  dropout: 0.0

  use_norm: ${use_norm_baseline}

pl_model: 
  _target_: src.models.gp.GaussianProcess
  learning_rate: ${params.gp.learning_rate}
  use_feature_extractor: False
  jitter: 1e-4

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 2

data: 
  batch_size: 32 # 256