name: "gp"
n_points: ${params.gp.n_points} 
strategy: "kmeans" # find inducing points using "kmeans" or "random" randomly sample inducing points

model:
  _target_: src.models.gp.GPModel
  num_latents: ${params.gp.num_latents}
  num_tasks: ${prediction_window}
  kernel: ${params.gp.kernel} 
  periodic_type: ${params.gp.periodic_type}
  use_linear_trend: ${params.gp.use_linear_trend} 

pl_model: 
  _target_: src.models.gp.GaussianProcess
  learning_rate: ${params.gp.learning_rate}
  jitter: 1e-4

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 2

data: 
  batch_size: 32 # 256