defaults:
  - base_module

name: "gp"
n_points: 250
strategy: "kmeans" # find inducing points using "kmeans" or "random" randomly sample inducing points

model:
  _target_: src.models.gp.Model
  
  use_feature_extractor: ${model.pl_model.use_feature_extractor}
  
  # GP layer
  num_latents: 10
  num_tasks: ${prediction_window}
  kernel: "matern"
  periodic_type: "" 
  use_linear_trend: True 

  #Feature Extractor
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim}
  hidden_dim: 8
  out_dim: 16
  dropout: 0.0


pl_model: 
  _target_: src.models.gp.GaussianProcess
  learning_rate: 0.001 
  use_feature_extractor: False
  jitter: 1e-4

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 2

data: 
  batch_size: 256