model_name: "GPT4TS"

model:
  _target_: src.models.gpt4ts.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  ln: 0 
  patch_size: 1
  stride: 1
  d_ff: 128
  d_model: 128
  enc_in: 1
  c_out: 1
  gpt_layers: 6
  embed: 'timeF' # time features encoding, options:[timeF, fixed, learned]
  freq: 'm'


pl_model: 
  _target_: src.models.gpt4ts.GPT4TS
  learning_rate: 0.002
  loss: 'SMAPE'
  lradj: "type1" # lr * 0.5**(epoch - 1 // 1)


trainer: 
  max_epochs: 100
  use_early_stopping: False

data:
  batch_size: 1