name: "hlinear"

model: 
  _target_: src.models.hlinear.HLinearModel
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

pl_model: 
  _target_: src.models.hlinear.HLinear
  learning_rate: 0.001 
  loss: ${loss_fn}

trainer:
  max_epochs: 1
  use_early_stopping: False
  patience: 2

data:
  batch_size: 256
