name: "hmm"

model:
  _target_: src.models.hmm.LinearAutoregressiveHMM # dummy model we use hmmlearn
  n_states: 2
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim} 
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

pl_model: 
  _target_: src.models.hmm.HMM
  learning_rate: 0.001
  optimizer_name: "lbfgs"

trainer:
  max_epochs: 100
  use_early_stopping: False
  patience: 2

data: 
  batch_size: 1