name: "hmm"

model:
  _target_: src.models.hmm.PytorchHMM
  base_dim: 128
  target_channel_dim: ${dataset.datamodule.target_channel_dim}
  temperature: 1.0
  min_var: 1e-6
  use_activity_labels: ${use_static_features}
  n_activity_states: ${dataset.datamodule.static_exogenous_variables}

pl_model: 
  _target_: src.models.hmm.HMMLightningModule
  learning_rate: 0.01
  deterministic: True

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 5

data: 
  batch_size: 256