name: "kalmanfilter"

model: 
  _target_: src.models.kalmanfilter.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.base_channel_dim}
  input_channels: ${dataset.input_channels}

pl_model: 
  _target_: src.models.kalmanfilter.KalmanFilter
  learning_rate: 0.01
  loss: "MSE"

trainer:
  max_epochs: 5
  use_early_stopping: False 

data:
  batch_size: 32
