name: "kalmanfilter"

model: 
  _target_: src.models.kalmanfilter.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim}
  hidden_dim: 32
  use_dynamic_features: ${use_dynamic_features}
  dynamic_exogenous_variables: ${dataset.datamodule.dynamic_exogenous_variables}

pl_model: 
  _target_: src.models.kalmanfilter.KalmanFilter
  learning_rate: 0.0005
  loss: "MSE"

trainer:
  max_epochs: 30
  use_early_stopping: True
  patience: 2

data:
  batch_size: 256
