name: "linear"

model: 
  _target_: src.models.mlp.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.datamodule.target_channel_dim}
  input_channels: ${dataset.datamodule.look_back_channel_dim}
  activation: "none"
  n_hid_layers: 0

pl_model: 
  _target_: src.models.linear.Linear
  learning_rate: ${params.linear.learning_rate} 
  loss: ${loss_fn}
  use_scheduler: False
  weight_decay: ${params.linear.weight_decay} 

trainer:
  max_epochs: 1000
  use_early_stopping: True
  patience: 2

data:
  batch_size: 256
