name: "linear"

model: 
  _target_: src.models.mlp.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.datamodule.target_channel_dim}
  input_channels: ${dataset.datamodule.look_back_channel_dim}
  activation: "none"
  n_hid_layers: 0

pl_model: 
  _target_: src.models.linear.Linear
  learning_rate: 0.008255574697066323
  loss: "MSE"
  use_scheduler: False
  weight_decay: 4.474906030033394e-06

trainer:
  max_epochs: 10
  use_early_stopping: True
  patience: 2

data:
  batch_size: 32
