defaults:
  - base_module

name: "linear"

model: 
  _target_: src.models.linear.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

  model_type: "ols"
  alpha: 1.0 # ridge alpha

pl_model: 
  _target_: src.models.linear.Linear
  loss: ${loss_fn}

trainer:
  max_epochs: 1
  use_early_stopping: False
  patience: 2

data:
  batch_size: 256
