name: "llmtime"

model:
  _target_: src.models.llmtime.DummyModel

pl_model:
  _target_: src.models.llmtime.LLMTime 
  prediction_window: ${prediction_window}


trainer:
  max_epochs: 0
  use_early_stopping: False 
  patience: 1

data:
  batch_size: 32