name: "mlp"

model: 
  _target_: src.models.mlp.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.datamodule.target_channel_dim}
  input_channels: ${dataset.datamodule.look_back_channel_dim}
  hid_dim: 32
  n_hid_layers: 2
  activation: "relu" # can be tanh, relu or none
  autoregressive: True
  use_norm: ${use_norm_baseline}

pl_model: 
  _target_: src.models.mlp.MLP
  learning_rate: 0.001
  loss: ${loss_fn}

trainer:
  max_epochs: 10000
  use_early_stopping: True
  patience: 5

data:
  batch_size: 256
