name: "msar"

model:
  _target_: src.models.msar.LinearAutoregressiveHMM # dummy model we use hmmlearn
  prediction_window: ${prediction_window}
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim} 
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

  # tunable parameters
  look_back_window: ${look_back_window}
  n_states: 2

  jitter: 1e-4
  sigma_min: 1e-2

  use_norm: ${use_norm_baseline}

pl_model: 
  _target_: src.models.msar.HMM
  learning_rate: 0.01
  weight_decay: 0.0
  optimizer_name: "adamw"

trainer:
  max_epochs: 10000
  use_early_stopping: True
  patience: 2

  gpu_mem: 4 
  n_gpus: 1

data: 
  batch_size: 16