
name: "naive"

model:
  _target_: src.models.naive.DummyModel
  use_trend: ${model.pl_model.use_trend}
  prediction_window: ${prediction_window}

pl_model: 
  _target_: src.models.naive.Naive
  use_trend: False

trainer:
  max_epochs: 0
  use_early_stopping: True
  patience: 5

data:
  batch_size: 256
  num_workers: ${num_workers}

