name: "pattn"

model:
  _target_: src.models.pattn.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  patch_size: 4 
  d_model: 128 

pl_model: 
  _target_: src.models.pattn.PAttn
  learning_rate: 0.002 
  lradj: 'type1'
  tmax: 10 

trainer: 
  max_epochs: 1000
  use_early_stopping: True
  patience: 5 

data:
  batch_size: 256

