name: "pattn"

model:
  _target_: src.models.pattn.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  patch_size: 16
  d_model: 768

pl_model: 
  _target_: src.models.pattn.PAttn
  learning_rate: 0.00005
  lradj: 'type1'
  tmax: 20

trainer: 
  max_epochs: 10
  use_early_stopping: True
  patience: 5 

data:
  batch_size: 256

