name: "setar"

model: 
  _target_: src.models.setar.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  look_back_channel_dim: ${dataset.datamodule.look_back_channel_dim}
  target_channel_dim: ${dataset.datamodule.target_channel_dim}

  # n_regimes = 1 is equivalent to batched linear regression
  n_regimes: 8 # number of regimes
  dropout: 0.0
  input_dropout: 0.0

  use_last: False
  revin: True

pl_model: 
  _target_: src.models.setar.SETAR
  loss_fn: ${loss_fn}
  learning_rate: 0.001
  weight_decay: 0.0
  optimizer_name: "adamw" # can be 'adam', 'adamw' or 'lbfgs'

trainer:
  max_epochs: 10000
  use_early_stopping: True
  patience: 2 

data:
  batch_size: 8
