defaults:
  - base_module

name: "simpletm"

model:
  _target_: src.models.simpletm.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  n_channels: ${dataset.datamodule.look_back_channel_dim}
  alpha: 1 
  kernel_size: 3  
  wv: "db1"
  factor: 1 # does nothing in the code! 
  requires_grad: True # set to true to enable trainable wavelets
  output_attention: False # has to be false, otherwise no attn is returned
  m: 3 # Number of levels for the stationary wavelet transform 

  # tunable parameters
  e_layers: 1 
  d_model: 256
  d_ff: 32 
  dropout: 0.015 
  geomattn_dropout: 0.25 

  
pl_model: 
  _target_: src.models.simpletm.SimpleTM
  learning_rate: 0.004 
  lradj: 'type1'
  loss_fn: ${loss_fn}

trainer: 
  max_epochs: 20 # we use 20 as the paper uses epochs=20 for the short-range PEMS dataset
  use_early_stopping: True
  patience: 5
  pct_start: 0.2

data:
  batch_size: 256