name: "simpletm"

model:
  _target_: src.models.simpletm.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  e_layers: 1
  output_attention: False # has to be false, otherwise no attn is returned
  use_norm: True # instance normalization in forward function of the model
  alpha: 1 
  kernel_size: 3  
  n_channels: ${dataset.datamodule.look_back_channel_dim}
  d_model: 256
  wv: "db1"
  factor: 1 # TODO: find out what this is doing
  dropout: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.dropout} 
  geomattn_dropout: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.geomattn_dropout} 
  requires_grad: True # set to true to enable trainable wavelets
  m: 3 # Number of levels for the stationary wavelet transform 
  d_ff: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.d_ff} # Dimensionality of the feed forward network

pl_model: 
  _target_: src.models.simpletm.SimpleTM
  learning_rate: ${params.${dataset.name}.${str:${use_dynamic_features}}.${str:${look_back_window}}.${str:${prediction_window}}.learning_rate} 
  lradj: 'type1'

trainer: 
  max_epochs: 1000
  use_early_stopping: True
  patience: 5
  pct_start: 0.2

data:
  batch_size: 256