name: "simpletm"

model:
  _target_: src.models.simpletm.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  n_channels: ${dataset.datamodule.look_back_channel_dim}
  use_norm: True # instance normalization in forward function of the model
  alpha: 1 
  kernel_size: 3  
  wv: "db1"
  factor: 1 # TODO: find out what this is doing
  requires_grad: True # set to true to enable trainable wavelets
  output_attention: False # has to be false, otherwise no attn is returned
  m: 3 # Number of levels for the stationary wavelet transform 

  # tunable parameters
  e_layers: ${params.simpletm.e_layers} # number of encoder layers
  d_model: ${params.simpletm.d_model}
  d_ff: ${params.simpletm.d_ff} 
  dropout: ${params.simpletm.dropout} 
  geomattn_dropout: ${params.simpletm.geomattn_dropout}

pl_model: 
  _target_: src.models.simpletm.SimpleTM
  learning_rate: ${params.simpletm.learning_rate}
  lradj: 'type1'

trainer: 
  max_epochs: 1000
  use_early_stopping: True
  patience: 5
  pct_start: 0.2

data:
  batch_size: 256