name: "simpletm"

model:
  _target_: src.models.simpletm.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  e_layers: 1
  output_attention: False # has to be false, otherwise no attn is returned
  use_norm: True # instance normalization in forward function of the model
  alpha: 1 
  kernel_size: 3  
  n_channels: ${dataset.input_channels}
  d_model: 512
  # embed_type: 0 # '0: default 1: value embedding + temporal embedding + positional embedding 2: value embedding + temporal embedding 3: value embedding + positional embedding 4: value embedding'
  # embed: 'timeF' # time features encoding, options:[timeF, fixed, learned]
  wv: "db1"
  factor: 1 # TODO: find out what this is doing
  dropout: 0.1
  geomattn_dropout: 0.5
  requires_grad: True # set to true to enable trainable wavelets
  m: 3 # Number of levels for the stationary wavelet transform 
  d_ff: 32 # Dimensionality of the feed forward network



pl_model: 
  _target_: src.models.simpletm.SimpleTM
  learning_rate: 0.02
  lradj: 'type1'

trainer: 
  max_epochs: 10
  use_early_stopping: True
  patience: 3
  pct_start: 0.2

data:
  batch_size: 256