name: "timexer"

model:
    _target_: src.models.timexer.Model
    use_exo_endo: ${use_dynamic_features} # should we use exogenous variables?
    pred_len: ${prediction_window}
    seq_len: ${look_back_window} 
    target_channel_dim: ${dataset.datamodule.target_channel_dim}
    look_back_window: ${look_back_window}
    enc_in: ${dataset.datamodule.look_back_channel_dim}
    embed: "timeF"
    freq: "h"
    factor: 1 # attention factor: afaik not used in the code!
    n_heads: 8
    activation: "gelu"

    # tunable params
    patch_len: 2 # code checks & sets: ${min:${look_back_window}, patch_len} 
    d_model: 128 
    d_ff: 256
    e_layers: 4 
    dropout: 0.1 

    use_norm: ${use_norm_dl}

pl_model:
    _target_: src.models.timexer.TimeXer
    learning_rate: 0.0001
    loss_fn: ${loss_fn}

trainer:
    max_epochs: 1000
    use_early_stopping: True 
    patience: 5

    gpu_mem: 24 
    n_gpus: 1

data:
    batch_size: 256 # 128