
model_name: "TimesNet"

model:
  _target_: src.models.timesnet.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  c_out: 1
  top_k: 5
  d_model: 32
  d_ff: 32
  num_kernels: 6
  e_layers: 2
  enc_in: 1
  dropout: 0.0


pl_model: 
  _target_: src.models.timesnet.TimesNet
  learning_rate: 0.001