model_name: "TimeLLM"

model:
  _target_: src.models.timellm.Model
  seq_len: ${look_back_window}
  pred_len: ${prediction_window}
  llama_model_path: ""
  dec_in: 7
  d_model: 512
  n_heads: 8
  individual: True
  dim: 10
  embed_type: 0 # '0: default 1: value embedding + temporal embedding + positional embedding 2: value embedding + temporal embedding 3: value embedding + positional embedding 4: value embedding'
  embed: 'timeF' # time features encoding, options:[timeF, fixed, learned]
  dropout: 0.1
  d_ff: 32 # Dimensionality of the feed forward network



pl_model: 
  _target_: src.models.simpletm.SimpleTM
  learning_rate: 0.001