
model_name: "TimesNet"

model:
  _target_: src.models.timesnet.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  e_layers: 2
  top_k: 5
  d_model: 32 # chosen according to min(max(2^log(C), d_min), d_max) Long-term: (d_min=32, d_max=512) |  Short-term: (d_min=16, d_max=64) 
  c_out: 1
  d_ff: 32
  num_kernels: 6
  enc_in: 1
  dropout: 0.0


pl_model: 
  _target_: src.models.timesnet.TimesNet
  learning_rate: 0.0001
  loss: 'MSE' # Long-term Loss = 'MSE' | Short-term Loss = 'SMAPE'
  optimizer: 'Adam'
  beta_1: 0.9
  beta_2: 0.999
  # use_amp: False

trainer: 
  max_epochs: 10
  patience: 3

data:
  batch_size: 3 # Long-term batch_size = 32 | Short-term batch_size = 16
