# @package _global_

look_back_window: 24

model:
  model:
    n_estimators: 631
    max_depth: 2
    reg_alpha: 0.0006
    reg_lambda: 0.038
    subsample: 0.680
    colsample_bytree: 0.863
    learning_rate: 0.0319