# @package _global_

look_back_window: 23

model:
  model:
    n_estimators: 830
    max_depth: 9 
    reg_alpha: 0.00006 
    reg_lambda: 0.167
    subsample: 0.875
    colsample_bytree: 0.844
    learning_rate: 0.0204