# @package _global_

look_back_window: 20

model:
  model:
    n_estimators: 616
    max_depth: 2
    reg_alpha: 0.0
    reg_lambda: 0.0
    subsample: 0.938
    colsample_bytree: 0.999
    learning_rate: 0.05