# @package _global_

model:
  model:
    colsample_bytree: 0.9143
    learning_rate: 0.2465
    max_depth: 6
    n_estimators: 776
    reg_alpha: 0.0001
    reg_lambda: 2.1908
    subsample: 0.8607
