# @package _global_

model:
  model:
    colsample_bytree: 0.7207
    learning_rate: 0.0155
    max_depth: 5
    n_estimators: 884
    reg_alpha: 2.7391
    reg_lambda: 25.936
    subsample: 0.7778
