# @package _global_

model:
  model:
    colsample_bytree: 0.7716
    learning_rate: 0.1359
    max_depth: 2
    n_estimators: 183
    reg_alpha: 5.7956
    reg_lambda: 0.0023
    subsample: 0.5757
