# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.0711
    dropout_prob_theta: 0.2643
    kernel_size: 2
    n_hidden: 100
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.0017
    weight_decay: 0.0
