# @package _global_

model:
  pl_model:
    learning_rate: 0.0044
    weight_decay: 0.00003
  model:
    stack_types: ["exogenous_tcn", "identity"]
    
    n_hidden: 100
    kernel_size: 4

    dropout_prob_theta: 0.001
    dropout_prob_exogenous: 0.119