# @package _global_

model:
  pl_model:
    learning_rate: 0.004
    weight_decay: 0.00001
  model:
    stack_types: ["exogenous_tcn", "identity"]
    
    n_hidden: 250
    kernel_size: 4

    dropout_prob_theta: 0.148
    dropout_prob_exogenous: 0.366