# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.2239
    dropout_prob_theta: 0.2793
    kernel_size: 5
    n_hidden: 100
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.0009
    weight_decay: 0.0
