# @package _global_

model:
  pl_model:
    learning_rate: 0.0016
    weight_decay: 0.00003
  model:
    stack_types: ["exogenous_tcn", "identity"]
    
    n_hidden: 250
    kernel_size: 3

    dropout_prob_theta: 0.018
    dropout_prob_exogenous: 0.426