# @package _global_

model:
  pl_model:
    learning_rate: 0.002
    weight_decay: 0.00003
  model:
    stack_types: ["exogenous_tcn", "identity"]
    
    n_hidden: 250
    kernel_size: 4

    dropout_prob_theta: 0.197
    dropout_prob_exogenous: 0.224