# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4994
    dropout_prob_theta: 0.2587
    kernel_size: 2
    n_hidden: 100
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.0011
    weight_decay: 0.0
