# @package _global_

look_back_window: 18

model:
  pl_model:
    learning_rate: 0.0024
    weight_decay: 0.00007
  model:
    stack_types: ["exogenous_wavenet", "identity"]
    
    n_hidden: 393
    kernel_size: 4

    dropout_prob_theta: 0.031
    dropout_prob_exogenous: 0.164