# @package _global_


model:
  pl_model:
    optimizer_name: "adam"
    learning_rate: 0.0099
    weight_decay: 0.000001
  model:
    n_regimes: 2
    use_last: True 
    dropout: 0.1
    input_dropout: 0.2
  data:
    batch_size: 64