# @package _global_

look_back_window: 20

model:
  pl_model:
    optimizer_name: "adamw"
    learning_rate: 0.0034
    weight_decay: 0.00001
  model:
    n_regimes: 32
    use_last: True
    dropout: 0.1
    input_dropout: 0.0
  data:
    batch_size: 64