# @package _global_

model:
  model:
    n_estimators: 684
    max_depth: 8
    reg_alpha: 0.076
    reg_lambda: 0.003
    subsample: 0.705
    colsample_bytree: 0.926
    learning_rate: 0.026