# @package _global_

look_back_window: 10

model:
  model:
    n_estimators: 740
    max_depth: 9
    reg_alpha: 0.1709
    reg_lambda: 0.7477
    subsample: 0.932
    colsample_bytree: 0.964
    learning_rate: 0.014