# @package _global_

model:
  model:
    colsample_bytree: 0.6071
    learning_rate: 0.0002
    max_depth: 8
    n_estimators: 197
    reg_alpha: 0.1344
    reg_lambda: 0.0019
    subsample: 0.6356
