name: "hmm"

model:
  _target_: src.models.hmm.PytorchHMM
  hidden_dim: 32 
  target_channel_dim: ${dataset.datamodule.target_channel_dim}
  temperature: 1.0
  min_var: 1e-6
  use_dynamic_features: ${dataset.datamodule.use_dynamic_features}
  dynamic_exogenous_variables: ${dataset.datamodule.dynamic_exogenous_variables}
  ff_dim: 16

pl_model: 
  _target_: src.models.hmm.HMMLightningModule
  learning_rate: 0.001
  deterministic: True

trainer:
  use_early_stopping: False
  max_epochs: 20

data: 
  batch_size: 256