name: "linear"

model: 
  _target_: src.models.mlp.Model
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  base_channel_dim: ${dataset.base_channel_dim}
  input_channels: ${dataset.input_channels}
  activation: "none"
  n_hid_layers: 0

pl_model: 
  _target_: src.models.linear.Linear
  learning_rate: 0.01
  loss: "MSE"

trainer:
  max_epochs: 10
  use_early_stopping: True
  patience: 2

data:
  batch_size: 32
