# @package _global_


model:
  pl_model:
    optimizer_name: "adam"
    learning_rate: 0.0034
    weight_decay: 0.0
  model:
    n_regimes: 32
    use_last: False 
    dropout: 0.1
    input_dropout: 0.2  
  
  data:
    batch_size: 512