# @package _global_

model:
  pl_model:
    optimizer_name: "adam"
    learning_rate: 0.002
    weight_decay: 0.0001
  model:
    n_regimes: 8
    use_last: True 
    dropout: 0.2
    input_dropout: 0.2  
  
  data:
    batch_size: 1024