# @package _global_

model:
  pl_model:
    optimizer_name: "adamw"
    learning_rate: 0.0001
    weight_decay: 0.0
  model:
    n_regimes: 16
    use_last: True 
    dropout: 0.2
    input_dropout: 0.0
  
  data:
    batch_size: 256