# @package _global_

model:
  pl_model:
    optimizer_name: "adamw"
    learning_rate: 0.0003
    weight_decay: 0.00001
  model:
    n_regimes: 4
    use_last: True 
    dropout: 0.1
    input_dropout: 0.2
  
  data:
    batch_size: 512