# @package _global_

look_back_window: 13

model:
  pl_model:
    optimizer_name: "adam"
    learning_rate: 0.001
    weight_decay: 0.0001
  model:
    n_regimes: 4
    use_last: False 
    dropout: 0.0 
    input_dropout: 0.0  
  
  data:
    batch_size: 8