# @package _global_

model:
  model:
    d_ff: 512
    d_model: 256
    dropout: 0.0164
    e_layers: 4
    n_heads: 8
    patch_len: 9
    stride: 3
  pl_model:
    learning_rate: 0.0002
