# @package _global_

model:
  model:
    d_ff: 32
    d_model: 64
    dropout: 0.2655
    e_layers: 2
    n_heads: 4
    patch_len: 16
    stride: 6
  pl_model:
    learning_rate: 0.0069
