# @package _global_

model:
  model:
    d_ff: 16
    d_model: 256
    dropout: 0.0264
    e_layers: 1
    n_heads: 16
    patch_len: 10
    stride: 6
  pl_model:
    learning_rate: 0.0001
