# @package _global_

model:
  model:
    n_estimators: 896
    max_depth: 7
    reg_alpha: 0.0
    reg_lambda: 0.001
    subsample: 0.782
    colsample_bytree: 0.980
    learning_rate: 0.008