# @package _global_

model:
  model:
    n_estimators: 638
    max_depth: 6
    reg_alpha: 0.396
    reg_lambda: 0.018
    subsample: 0.745
    colsample_bytree: 0.941
    learning_rate: 0.081