defaults:
 -  shared_sweeper

params:
  model.trainer.use_early_stopping: True
  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))

  model.model.d_model: choice(128, 256, 512, 768)
  model.model.inner_size: choice(2, 4, 8, 16)

  # model.data.batch_size: choice(32, 64, 128, 256)
