defaults:
 -  shared_sweeper

params:
  model.trainer.use_early_stopping: False
  model.pl_model.optimizer: "em"
  model.pl_model.deterministic: True
  model.pl_model.n_states: int(interval(2, 100))
  model.pl_model.n_iter: int(interval(10, 300)) 
  model.pl_model.transition_matrix_stickiness: interval(0, 50)
