defaults:
 -  shared_sweeper

params:
  model.trainer.max_epochs: 50
  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))

  model.model.dropout: interval(0.0, 0.3)
  model.model.t_layers: choice(1, 2, 4)
  model.model.f_hidden_size: choice(32, 64, 128, 256, 512)
  model.model.d_inner: choice(32, 64, 128, 256, 512)

  model.data.batch_size: choice(32, 64, 128, 256)

