defaults:
 -  shared_sweeper

params:
  model.trainer.max_epochs: 20
  model.model.hidden_dim: int(interval(8, 1024))
  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))
  model.pl_model.loss:  choice("MSE", "MAE", "SMAPE") 
  # model.data.batch_size: choice(32, 64, 128, 256)

