defaults:
 -  shared_sweeper

params:

  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))
  model.pl_model.weight_decay: tag(log, interval(1e-8, 1.0))

  model.model.state_dim: choice(4, 8, 16, 32, 64, 128) 


