defaults:
 -  shared_sweeper

params:
  model.pl_model.learning_rate: tag(log, interval(1e-5, 0.01))
  model.model.hid_dim: choice(8,16,32,64,128,256,512)
  model.model.n_hid_layers: choice(1,2,3,4)
  model.model.dropout: interval(0.0,0.5)