defaults:
 -  shared_sweeper

params:
  model.pl_model.learning_rate: choice(3e-4, 1e-3, 3e-3) # tag(log, interval(1e-5, 0.01))
  model.pl_model.weight_decay: choice(0.0, 1e-6, 1e-5, 1e-4, 5e-4)

  model.model.hid_dim: choice(8,16,32,64,128)
  model.model.n_hid_layers: choice(1,2,3,4)
  model.model.dropout: interval(0.0,0.1)
  model.model.activation: choice("relu", "gelu", "tanh", "sigmoid")

