defaults:
 -  shared_sweeper

params:

  model.pl_model.learning_rate: tag(log, interval(5e-4, 1e-2))
  model.pl_model.optimizer: choice("adam", "lbfgs", "adamw")
  model.pl_model.weight_decay: tag(log, interval(1e-5, 1.0))

  model.model.n_states: choice(1,2,4,8,16) 



