defaults:
 -  shared_sweeper

params:
  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))

  model.model.e_layers: choice(1, 2, 3, 4)
  model.model.d_model: choice(16, 32, 64, 128, 256, 512)
  model.model.d_ff: choice(16, 32, 64, 128, 256, 512)
  model.model.dropout: interval(0.0, 0.5)
  model.model.n_heads: choice(4, 8, 16)

  model.model.patch_len: int(interval(2,16))
  model.model.stride: int(interval(1,8))

