defaults:
 -  shared_sweeper

params:
  model.trainer.max_epochs: 50
  model.trainer.use_early_stopping: True 
  
  model.pl_model.learning_rate: tag(log, interval(1e-5, 1e-2))
  model.pl_model.tmax: choice(10, 20, 50)

  model.model.patch_size: choice(4, 8, 16, 32)
  model.model.d_model: choice(128, 256, 512, 768)

  # model.data.batch_size: choice(32, 64, 128, 256)

