defaults:
 -  shared_sweeper

params:
  model.pl_model.learning_rate: tag(log, interval(1e-5, 0.01))
  model.model.hidden_dim: choice(1,2,4,8,16,32,64)
  model.model.n_regimes: int(interval(1,11))