sampler:
  _target_: optuna.samplers.TPESampler        
  seed: null
  consider_prior: true
  prior_weight: 1.0
  consider_magic_clip: true
  consider_endpoints: false
  n_startup_trials: 10
  n_ei_candidates: 24
  multivariate: false
  warn_independent_sampling: true
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction: minimize
storage: null
study_name: ${optuna_name:${dataset.name}, ${model.name}, ${use_heart_rate}, ${look_back_window}, ${prediction_window}, ${folds.fold_nr}, ${fold_datasets}, ${normalization}, ${experiment.experiment_name}} 
n_trials: ${n_trials}
n_jobs: 1
search_space: null
custom_search_space: null
# max_failure_rate: 0.5 does not work
use_wandb: True  
metric_name: "val_loss"
wandb_kwargs:
  project: ${wandb.project}
  name: ${hydra.sweeper.study_name}
  reinit: True 
  dir: ${path.basedir}

params:
  model.data.batch_size: 256