defaults:
 -  shared_sweeper

params:
  model.trainer.max_epochs: 50
  model.trainer.use_early_stopping: True

  model.pl_model.learning_rate: tag(log, interval(1e-5, 5e-2))

  model.model.d_ff: choice(32, 64, 128, 256, 512)
  model.model.dropout: interval(0.0, 0.5)
  model.model.llm_dim: choice(256, 512, 1024, 2048, 4096, 8192)
  model.model.llm_layers: int(interval(3,8))
  model.model.n_heads: choice(4,6,8)


