defaults:
 -  shared_sweeper



params:
  model.trainer.use_early_stopping: True
  
  model.pl_model.learning_rate: tag(log, interval(1e-4, 5e-2))

  model.model.d_model: choice(16, 32, 64)
  model.model.d_ff: choice(16, 32, 64)
  model.model.dropout: interval(0.0, 0.5)
  
  