defaults:
 -  shared_sweeper

params:
  model.trainer.max_epochs: 50
  model.trainer.use_early_stopping: True

  model.pl_model.learning_rate: tag(log, interval(1e-5, 5e-2))

  model.model.d_ff: choice(32, 64, 128, 256, 512)
  model.model.d_model: choice(4, 8, 16, 32, 64)
  # model.model.llm_layers: choice(4, 8, 16, 32) 
  model.model.llm_layers: 4
  model.model.dropout: interval(0.0, 0.5)


