defaults:
 -  shared_sweeper



params:
  model.trainer.max_epochs: 50
  model.trainer.use_early_stopping: True
  model.pl_model.learning_rate: tag(log, interval(1e-4, 5e-2))
  model.model.d_model: choice(32, 64, 128, 256, 512)
  model.model.d_ff: choice(32, 64, 128)
  model.model.dropout: interval(0.0, 0.3)
  model.model.top_k: choice(3, 5, 7, 9)
  
  # model.data.batch_size: choice(32, 64, 128, 256)