defaults:
 -  shared_sweeper

params:
  model.model.learning_rate: tag(log, interval(1e-4, 1e-1))
  model.model.n_estimators: int(interval(100, 1000))
  model.model.max_depth: int(interval(2,12)) 
  model.model.reg_alpha: tag(log, interval(1e-5, 10.0))
  model.model.reg_lambda: tag(log, interval(1e-5, 10.0))
  model.model.subsample: interval(0.5, 1.0)
  model.model.colsample_bytree: interval(0.5, 1.0) 
