defaults:
 -  shared_sweeper

params:
  model.model.learning_rate: interval(1e-4, 2.0) # tag(log, interval(1e-4, 2.0))
  model.model.n_estimators: 500 # int(interval(50, 1000))
  model.model.max_depth: int(interval(2,12)) 
  model.model.reg_alpha: interval(1e-5, 10.0) # tag(log, interval(1e-5, 10.0))
  model.model.reg_lambda: interval(1e-5, 10.0) # tag(log, interval(1e-5, 10.0))
  model.model.subsample: interval(0.5, 1.0)
  model.model.colsample_bytree: interval(0.5, 1.0) 
