# @package _global_

model:
  model:
    d_ff: 512
    d_model: 32
    dropout: 0.0254
    e_layers: 2
    n_heads: 16
    patch_len: 4
    stride: 6
  pl_model:
    learning_rate: 0.0015
