# @package _global_

model:
  data:
    batch_size: 64
  model:
    dropout: 0
    input_dropout: 0.2
    n_regimes: 32
    use_last: true
  pl_model:
    learning_rate: 0.0002
    optimizer_name: adam
    weight_decay: 0.0001
