# @package _global_

model:
  data:
    batch_size: 256
  model:
    dropout: 0
    input_dropout: 0.3
    n_regimes: 8
    use_last: true
  pl_model:
    learning_rate: 0.002
    optimizer_name: adamw
    weight_decay: 0
