# @package _global_

model:
  model:
    n_estimators: 602
    max_depth: 5
    reg_alpha: 76.838
    reg_lambda: 5.557
    subsample: 0.777
    colsample_bytree: 0.968
    learning_rate: 0.022