# @package _global_

model:
  model:
    n_estimators: 932
    max_depth: 2
    reg_alpha: 0.039
    reg_lambda: 0.0
    subsample: 0.733
    colsample_bytree: 0.967
    learning_rate: 0.016