# @package _global_

look_back_window: 10
model:
  model:
    colsample_bytree: 0.8366
    learning_rate: 0.0011
    max_depth: 3
    n_estimators: 947
    reg_alpha: 38.8963
    reg_lambda: 0.0097
    subsample: 0.6522
