# @package _global_

model:
  model:
    d_ff: 256
    d_model: 256
    dropout: 0.1031
    e_layers: 4
    n_heads: 8
    patch_len: 4
    stride: 1
  pl_model:
    learning_rate: 0.0006
