# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4393
    dropout_prob_theta: 0.2748
    kernel_size: 3
    n_hidden: 100
    stack_types:
    - exogenous_tcn
    - identity
  pl_model:
    learning_rate: 0.0075
    weight_decay: 0.0013
