# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.1358
    dropout_prob_theta: 0.1846
    kernel_size: 2
    n_hidden: 250
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.001
    weight_decay: 0.0
