defaults:
  - _self_
  - model: timesnet
  - dataset: dalia
  - path: local

hydra:
  run:
    dir: ${path.basedir}/outputs

# most important params
look_back_window: 5
prediction_window: 3
use_heart_rate: True
use_activity_info: False

seed: 123
use_wandb: False
overfit: True
use_checkpoint_callback: False
num_workers: 0

# wandb 
wandb:
  save_dir: ${path.basedir}/wandb_logs
  project: "thesis"
  log_model: False
  save_code: True
  reinit: True


# multi gpu training
use_multi_gpu: False
multi:
  accelerator: "gpu"
  devices: 4
  strategy: "ddp"




