defaults:
  - _self_
  - model: timesnet
  - dataset: dalia
  - path: local

# most important params
look_back_window: 5
prediction_window: 3
use_heart_rate: True
use_activity_info: False

seed: 123
use_wandb: False
overfit: True
use_checkpoint_callback: False
num_workers: 0


