defaults:
  - _self_
  - model: timesnet
  - dataset: dalia

seed: 123
overfit: True
look_back_window: 60
prediction_window: 10
use_activity_info: False

# data directories
cluster: True
cluster_data_dir: "/cluster/project/holz/ckeusch/euler"
local_data_dir:  "C:/Users/cleme/ETH/Master/Thesis/data/euler"
datadir: ${select:${cluster},${cluster_data_dir},${local_data_dir}}