defaults:
  - _self_
  - model: elastst
  - dataset: dalia
  - path: local

# most important params
look_back_window: 3
prediction_window: 1
use_heart_rate: False
use_activity_info: False

seed: 123
use_wandb: False
overfit: True
num_workers: 0


