defaults:
  - _self_
  - model: timesnet
  - dataset: dalia
  - path: cluster
  - experiment: fold_0
  # - override hydra/sweeper: pattn_sweeper

fold_datasets: ["dalia", "wildppg", "ieee", "ucihar", "usc"]

hydra:
  run:
    dir: ${path.basedir}/outputs

# most important params
look_back_window: 5
prediction_window: 3
use_heart_rate: True
use_static_features: False
use_dynamic_features: True

seed: 123
overfit: False
use_checkpoint_callback: True
num_workers: 0
use_plots: True

# wandb logging
use_wandb: False
wandb:
  save_dir: ${path.basedir}/wandb_logs
  project: "thesis"
  log_model: False
  save_code: True
  reinit: True

# tuner 
tune: False

# multi gpu training
use_multi_gpu: False
multi:
  accelerator: "gpu"
  devices: 4
  num_nodes: 1
  strategy: "ddp"




