defaults:
  - _self_
  - model: timesnet
  - dataset: dalia
  - path: local
  # - override hydra/sweeper: pattn_sweeper

hydra:
  run:
    dir: ${path.basedir}/outputs

# most important params
look_back_window: 5
prediction_window: 3
use_heart_rate: True
use_static_features: True 
use_dynamic_features: True

use_activity_info: False

seed: 123
overfit: False
use_checkpoint_callback: False
num_workers: 0

# wandb logging
use_wandb: False
wandb:
  save_dir: ${path.basedir}/wandb_logs
  project: "thesis"
  log_model: False
  save_code: True
  reinit: True

# tuner 
tune: False

# multi gpu training
use_multi_gpu: False
multi:
  accelerator: "gpu"
  devices: 4
  strategy: "ddp"




