defaults:
  - _self_
  - model: timesnet
  - dataset: ieee
  - path: cluster
  - experiment: fold_0
  # - override hydra/sweeper: pattn_sweeper

n_folds: 3
fold_datasets: ["dalia", "wildppg", "ieee", "ucihar", "usc"] # these datasets have folds defined in config/experiments
special_models: ["bnn", "xgboost"] # these models are not trained with pytorch

hydra:
  run:
    dir: ${path.basedir}/outputs

# most important params
look_back_window: 5
prediction_window: 1 
use_heart_rate: True
use_static_features: False
use_dynamic_features: True

seed: 123
overfit: False
use_checkpoint_callback: True
num_workers: 0 # how many workers the pytorch dataloader has
use_plots: False # flag for plotting test predictions and test timeseries 

# wandb logging settings
use_wandb: False
wandb:
  save_dir: ${path.basedir}/wandb_logs
  project: "thesis"
  log_model: False
  save_code: True
  reinit: True

# tuner flag
tune: False
n_trials: 50
  
# multi gpu settings
use_multi_gpu: False
multi:
  accelerator: "gpu"
  devices: 4
  num_nodes: 1
  strategy: "ddp"




