defaults:
  - _self_
  - model: elastst
  - dataset: ieee
  - path: local

seed: 123
use_wandb: False
overfit: True
num_workers: 0
look_back_window: 128
prediction_window: 64
use_activity_info: False

