defaults:
  - _self_
  - model: elastst
  - dataset: dalia
  - path: local

seed: 123
use_wandb: False
overfit: True
num_workers: 0
look_back_window: 3
prediction_window: 1
use_activity_info: False

