# @package _global_

model:
  model:
    e_layers: 4 
    d_model: 64
    d_ff: 128
    dropout: 0.269 
    n_heads: 4
    patch_len: 10 
    stride: 3

  pl_model:
    learning_rate: 0.0003