# @package _global_

model:
  model:
    e_layers: 4
    d_model: 512
    d_ff: 256
    dropout: 0.239
    n_heads: 8
    patch_len: 12
    stride: 6

  pl_model:
    learning_rate: 0.00006