# @package _global_

look_back_window: 17

model:
  model:
    e_layers: 2 
    d_model: 256
    d_ff: 16
    dropout: 0.044
    n_heads: 8
    patch_len: 9
    stride: 8

  pl_model:
    learning_rate: 0.0001