# @package _global_

look_back_window: 30

model:
  model:
    e_layers: 4
    d_model: 128
    d_ff: 64
    dropout: 0.337
    n_heads: 8
    patch_len: 8
    stride: 6

  pl_model:
    learning_rate: 0.0002