fold_nr: 0

dalia:
  train_participants: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  val_participants:   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  test_participants:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

ieee:
  train_participants: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
  val_participants:   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
  test_participants:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 

wildppg:
  train_participants: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  val_participants:   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  test_participants:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


