fold_nr: 1

dalia:
  train_participants: [1, 2, 9, 11, 12, 13, 15]     
  val_participants:   [4, 5, 6]
  test_participants:  [3, 7, 8, 10, 14]

ieee:
  train_participants: [0, 1, 2, 5, 6, 11]
  val_participants:   [3, 10]
  test_participants:  [4, 7, 8, 9]
    
wildppg:
  train_participants: [0, 2, 3, 6, 8, 12, 14, 15]
  val_participants:   [1, 5, 9]
  test_participants:  [4, 7, 10, 11, 13]

