fold_nr: 2

dalia:
  train_participants: [1, 2, 4, 5, 6, 11, 13]       
  val_participants:   [9, 12, 15]
  test_participants:  [3, 7, 8, 10, 14]

ieee:
  train_participants: [0, 1, 2, 3, 5, 10]
  val_participants:   [6, 11]
  test_participants:  [4, 7, 8, 9]

wildppg:
  train_participants: [0, 1, 2, 3, 5, 8, 9, 12]
  val_participants:   [6, 14, 15]
  test_participants:  [4, 7, 10, 11, 13]

