fold_nr: 0

dalia:
  train_participants: [4, 5, 6, 9, 12, 13, 15]
  val_participants:   [1, 2, 11]
  test_participants:  [3, 7, 8, 10, 14]  

ieee:
  train_participants: [0, 2, 3, 6, 10, 11]
  val_participants:   [1, 5]
  test_participants:  [4, 7, 8, 9]

wildppg:
  train_participants: [0, 1, 3, 6, 9, 10]
  val_participants:   [7, 11, 13]
  test_participants:  [5, 12, 14, 15]
