# @package _global_

model:
  model:
    colsample_bytree: 0.8544
    learning_rate: 0.2109
    max_depth: 6
    n_estimators: 603
    reg_alpha: 0.1956
    reg_lambda: 1.9128
    subsample: 0.9559
