name: "capture24"

datamodule:
  _target_: src.datasets.capture24_dataset.Capture24DataModule
  data_dir: "${path.datadir}/Capture24/capture24_preprocessed/"
  batch_size: 32
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}

  freq: 25
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 3 
  dynamic_exogenous_variables: 1 # MET score 
  static_exogenous_variables: 5 # Categorical: AGE (4) | Binary: SEX (1s)
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}
