name: "chapman"
freq: 10 # TODO

datamodule:
  _target_: src.datasets.chapman_dataset.ChapmanDataModule
  data_dir: "${path.datadir}/Chapman/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  use_disease: ${use_activity_info}
  batch_size: 32

base_channel_dim: 4
activity_channel_dim: 4
input_channels: ${eval:'8 if ${use_activity_info} else 4'}
