name: "chapman"

datamodule:
  _target_: src.datasets.chapman_dataset.ChapmanDataModule
  data_dir: "${path.datadir}/Chapman/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  freq: 100 
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 4
  dynamic_exogenous_variables: 0 # we have no dynamic acceleration data for activity 
  static_exogenous_variables: 4 # 4 different disease classes 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}
