name: "dalia"
freq: 64  

datamodule:
  _target_: src.datasets.dalia_dataset.DaLiADataModule
  data_dir: "${path.datadir}/dalia_preprocessed"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [2, 3, 4, 5, 6, 7, 8, 12, 15]
  val_participants: [9, 10, 11] # 2 for validation
  test_participants: [1, 13, 14] # too small take 5 
  use_heart_rate: True
  use_activity_info: ${use_activity_info} 
  num_workers: ${num_workers}
  batch_size: 32

base_channel_dim: 1 
activity_channel_dim: 1
input_channels: ${eval:'2 if ${use_activity_info} else 1'} 
