name: "dalia"
description: "The PPG-DaLiA dataset is a multivariate time-series collection for heart rate estimation with motion compensation in daily life. It includes PPG, ECG (ground truth), and 3D accelerometer data from 15 subjects during various activities. Heart rate ground truth is derived from 8-second windows. This dataset is characterized by high sampling rates and real-world motion artifacts. LLMs should focus on identifying rhythmic physiological patterns, motion-induced noise correlations, and activity-specific signal changes to accurately predict heart rate."

datamodule:
  _target_: src.datasets.dalia_dataset.DaLiADataModule
  data_dir: "${path.datadir}/dalia_preprocessed"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: ${experiment.dalia.train_participants} 
  val_participants: ${experiment.dalia.val_participants} 
  test_participants: ${experiment.dalia.test_participants} 
  num_workers: ${num_workers}
  batch_size: ${model.data.batch_size}

  freq: 32
  name: ${dataset.name}
  
  use_heart_rate: ${use_heart_rate}
  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1 # dynamic activity information is locally normalized
  static_exogenous_variables: 12 # Continuous: AGE, HEIGHT, WEIGHT Binary: GENDER Categorical: SKIN, SPORT
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}