name: "dalia"

datamodule:
  _target_: src.datasets.dalia_dataset.DaLiADataModule
  data_dir: "${path.datadir}/dalia_preprocessed"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [2, 3, 4, 5, 6, 7, 8, 12, 15]
  val_participants: [9, 10] # 2 for validation
  test_participants: [1, 11, 13, 14, 15] 
  num_workers: ${num_workers}
  batch_size: ${model.data.batch_size}

  freq: 32
  name: ${dataset.name}
  
  use_heart_rate: ${use_heart_rate}
  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1 # dynamic activity information is locally normalized
  static_exogenous_variables: 12 # Continuous: AGE, HEIGHT, WEIGHT Binary: GENDER Categorical: SKIN, SPORT
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}