datamodule:
  _target_: src.datasets.dalia_dataset.DaLiADataModule
  data_dir: "${path.datadir}/dalia_preprocessed"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [2, 3, 4, 5, 6, 7, 8, 12, 15]
  val_participants: [9, 10, 11]
  test_participants: [1, 13, 14]
  use_heart_rate: False
  use_activity_info: ${use_activity_info} 
  batch_size: 32
