datamodule:
  _target_: src.datasets.DaLiADataModule
  data_dir: "C:/Users/cleme/ETH/Master/Thesis/data/DaLiA/data/PPG_FieldStudy"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [2, 3, 4, 5, 6, 7, 8, 12, 15]
  val_participants: [9, 10, 11]
  test_participants: [1, 13, 14]
  batch_size: 32
  use_heart_rate: False
