datamodule:
  _target_: src.datasets.DaLiADataModule
  data_dir: "C:/Users/cleme/ETH/Master/Thesis/data/DaLiA/data/PPG_FieldStudy"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  batch_size: 32
