name: null

datamodule:
  _target_: null
  data_dir: null 
  name: ${dataset.name}
  use_heart_rate: ${use_heart_rate}
  freq: null 
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}

  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: null 
  dynamic_exogenous_variables: null 
  static_exogenous_variables: null 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}
