name: "fdalia"

participants: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

datamodule:
  _target_: src.datasets.fdalia.FDalia
  data_dir: "${path.datadir}/dalia_preprocessed"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  participant: 1
  num_workers: ${num_workers}
  batch_size: ${model.data.batch_size}

  freq: 32
  name: ${dataset.name}
  
  use_heart_rate: ${use_heart_rate}
  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  window_statistic: "var" # can be "mean" "var" or "power"

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1 # dynamic activity information is locally normalized
  # static_exogenous_variables: 12 # Continuous: AGE, HEIGHT, WEIGHT Binary: GENDER Categorical: SKIN, SPORT
  static_exogenous_variables: 9 # we have 9 different activity types the participants perform
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}, ${use_only_exo}, ${use_perfect_info}}