name: "fieee"

participants: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 

datamodule:
  _target_: src.datasets.fieee.FIEEE
  data_dir: "${path.datadir}/IEEEPPG/Training_data/Training_data/ieee_preprocessed/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  participant: 0
  use_heart_rate: ${use_heart_rate}
  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  freq: 25 # preprocessed from 125Hz => 25Hz
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1
  static_exogenous_variables: 0 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}, ${use_only_exo}, ${use_perfect_info}}

