name: "ieee"
datamodule:
  _target_: src.datasets.ieee_dataset.IEEEDataModule
  data_dir: "${path.datadir}/IEEEPPG/Training_data/Training_data/ieee_preprocessed/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [0, 1, 2, 3, 4, 5, 6]
  val_participants: [8, 9]
  test_participants: [7, 10, 11]
  use_heart_rate: ${use_heart_rate}
  use_activity_info: ${use_activity_info}
  batch_size: 32
  num_workers: ${num_workers}

  freq: 25 # preprocessed from 125Hz => 25Hz
  name: ${dataset.name}

base_channel_dim: 1
activity_channel_dim: 1
input_channels: ${dataset.base_channel_dim}
