name: "ieee"
datamodule:
  _target_: src.datasets.ieee_dataset.IEEEDataModule
  data_dir: "${path.datadir}/IEEEPPG/Training_data/Training_data/ieee_preprocessed/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: ${experiment.ieee.train_participants} 
  val_participants: ${experiment.ieee.val_participants} 
  test_participants: ${experiment.ieee.test_participants}
  use_heart_rate: ${use_heart_rate}
  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  freq: 25 # preprocessed from 125Hz => 25Hz
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1
  static_exogenous_variables: 0 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}

