datamodule:
  _target_: src.datasets.ieee_dataset.IEEEDataModule
  data_dir: "${path.datadir}/IEEEPPG/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] 
  val_participants: [15, 16, 17, 18]
  test_participants: [19, 20, 21, 22]
  use_heart_rate: False
  batch_size: 32
  num_workers: ${num_workers}