datamodule:
  _target_: src.datasets.ieee_dataset.IEEEDataModuel
  data_dir: "C:/Users/cleme/ETH/Master/Thesis/data/IEEEPPG/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  # train_participants: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] 
  train_participants: [1]
  # val_participants: [15, 16, 17, 18]
  val_participants: [15]
  test_participants: [19, 20, 21, 22]
  use_heart_rate: False
  batch_size: 32