name: "mhc6mwt"

datamodule:
  _target_: src.datasets.mhc6mwt_dataset.MHC6MWTDataModule
  data_dir: "${path.datadir}/mhc6mwt/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  use_activity_info: ${use_activity_info}
  batch_size: 32
  num_workers: ${num_workers}

  freq: 1 # The freq is one, since we have one timestep per second
  name: ${dataset.name}

base_channel_dim: 1
activity_channel_dim: 2
dynamic_exogenous_variables: 0 # we have "dynamic" features DISTANCE & NUMBEROFSTEPS, but we dont normalize them
static_exogenous_variables: 6 # Continuous: AGE, Categorical: SEX (3), PHYSICAL_ACTIVITY (7)
input_channels: ${eval:'3 if ${use_activity_info} else 1'}
