name: "mhc6mwt"

datamodule:
  _target_: src.datasets.mhc6mwt_dataset.MHC6MWTDataModule
  data_dir: "${path.datadir}/mhc6mwt/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  random_state: ${seed}
  freq: 1 # The freq is one, since we have one timestep per second
  name: ${dataset.name}
  use_heart_rate: True

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1
  dynamic_exogenous_variables: 0 # we treat the n_steps and distance as static features
  # static_exogenous_variables: 12 # Continuous: AGE, Categorical: SEX (3), PHYSICAL_ACTIVITY (7) + n_steps 
  static_exogenous_variables: 1 # adds in only the already z-normalized velocity as activity info
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}



