name: "ptbxl"

datamodule:
  _target_: src.datasets.ptbxl_dataset.PTBXLDataModule
  data_dir: "${path.datadir}/PTBXL/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_folds: [1,2,3,4,5,6]
  val_folds: [7,8]
  test_folds: [9,10]
  batch_size: 32
  num_workers: ${num_workers}

  freq: 100
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 12 
  dynamic_exogenous_variables: 0 
  static_exogenous_variables: 7 # Continuous: AGE | Categorical: disease classes (6) NORM, MI, UNKNOWN, STTC, HYP, CD
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}


