name: "ucihar"

datamodule:
  _target_: src.datasets.ucihar_dataset.UCIHARDataModule
  data_dir: ${path.datadir}/UCIHAR/ 
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [1,  3,  5,  6,  7,  8, 11, 14, 15, 16, 17, 19, 21, 22]
  val_participants: [23, 25, 26, 27, 28, 29, 30]
  # we don't need test participants, since we get a train test split
  batch_size: ${model.data.batch_size}
  num_workers: ${num_workers}

  freq: 50
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 9
  dynamic_exogenous_variables: 0 
  static_exogenous_variables: 6 # 6 different classes for activity 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}}




