name: "usc"
datamodule:
  _target_: src.datasets.usc_dataset.USCDataModule
  data_dir: "C:/Users/cleme/ETH/Master/Thesis/data/USC/USC-HAD/"
  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}
  train_participants: [1, 2, 4, 5, 7, 10, 11, 14]
  val_participants: [3, 6, 8]
  test_participants: [9, 12, 13] 
  use_activity_info: ${use_activity_info}
  num_workers: ${num_workers}
  batch_size: 32

  freq: 100
  name: ${dataset.name}

base_channel_dim: 6 
activity_channel_dim: 12
input_channels: ${eval:'18 if ${use_activity_info} else 6'} 