name: "wildppg"
freq_acc: 200
freq_ppg: 25 # in the paper, they downsample the signal

datamodule:
  _target_: src.datasets.wildppg_dataset.WildPPGDataModule
  data_dir: "${path.datadir}/WildPPG/"

  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}

  train_participants: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  val_participants: [10, 11, 12]
  test_participants: [13, 14, 15]

  use_heart_rate: False
  use_activity_info: False

  batch_size: 1