defaults:
  - datamodule

name: "wildppg"

datamodule:
  _target_: src.datasets.wildppg_dataset.WildPPGDataModule
  data_dir: "${path.datadir}/WildPPG/"

  train_participants: ${folds.wildppg.train_participants}
  val_participants: ${folds.wildppg.val_participants}
  test_participants: ${folds.wildppg.test_participants} 

  sensor_location: ankle
  imu_features: ${feature.imu_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: ${number_of_exo_vars:${.imu_features}}
  static_exogenous_variables: 0 


