defaults:
  - datamodule

name: "wildppg"

datamodule:
  _target_: src.datasets.wildppg_dataset.WildPPGDataModule
  data_dir: "${path.datadir}/WildPPG8/"

  train_participants: ${folds.wildppg.train_participants}
  val_participants: ${folds.wildppg.val_participants}
  test_participants: ${folds.wildppg.test_participants} 

  imu_features:
    - ankle_rms
    - ankle_centroid
    - ankle_jerk
    - ankle_last2s_rms

  target_channel_dim: 1 
  dynamic_exogenous_variables: ${number_of_exo_vars:${.imu_features}}
  static_exogenous_variables: 0 


