name: "wildppg"

datamodule:
  _target_: src.datasets.wildppg_dataset.WildPPGDataModule
  data_dir: "${path.datadir}/WildPPG/"

  look_back_window: ${look_back_window}
  prediction_window: ${prediction_window}

  train_participants: ${folds.wildppg.train_participants}
  val_participants: ${folds.wildppg.val_participants}
  test_participants: ${folds.wildppg.test_participants} 

  use_heart_rate: ${use_heart_rate}
  num_workers: ${num_workers}
  batch_size: ${model.data.batch_size}

  freq: 25 # PPG signal in the paper, they downsample the signal to 25Hz
  name: ${dataset.name}

  use_dynamic_features: ${use_dynamic_features}
  use_static_features: ${use_static_features}

  target_channel_dim: 1 
  dynamic_exogenous_variables: 1
  static_exogenous_variables: 0 
  look_back_channel_dim: ${compute_input_channel_dims:${.target_channel_dim},${.dynamic_exogenous_variables},${.static_exogenous_variables},${.use_dynamic_features},${.use_static_features}, ${use_only_exo}}


