# @package _global_

model:
  data:
    batch_size: 256
  model:
    dropout: 0
    input_dropout: 0.1
    n_regimes: 32
    use_last: false
  pl_model:
    learning_rate: 0.0069
    optimizer_name: adam
    weight_decay: 0.0
