# @package _global_

model:
  data:
    batch_size: 256
  model:
    dropout: 0.1
    input_dropout: 0.4
    n_regimes: 32
    use_last: true
  pl_model:
    learning_rate: 0.002
    optimizer_name: adam
    weight_decay: 0
