# @package _global_

model:
  data:
    batch_size: 64
  model:
    dropout: 0.1
    input_dropout: 0.3
    n_regimes: 16
    use_last: true
  pl_model:
    learning_rate: 0.002
    optimizer_name: adamw
    weight_decay: 0.0
