# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.2671
    dropout_prob_theta: 0.1354
    kernel_size: 3
    n_hidden: 250
    stack_types:
    - identity
    - exogenous_tcn
  pl_model:
    learning_rate: 0.007
    weight_decay: 0.0
