# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4734
    dropout_prob_theta: 0.3138
    kernel_size: 2
    n_hidden: 250
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.0047
    weight_decay: 0.0001
