# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4996
    dropout_prob_theta: 0.1567
    kernel_size: 5
    n_hidden: 250
    stack_types:
    - identity
    - exogenous_tcn
  pl_model:
    learning_rate: 0.0065
    weight_decay: 0.0299
