# @package _global_

model:
  model:
    n_estimators: 401
    max_depth: 8
    reg_alpha: 0.059
    reg_lambda: 0.0
    subsample: 0.828
    colsample_bytree: 0.958
    learning_rate: 0.0289