# @package _global_

model:
  data:
    batch_size: 1024
  model:
    dropout: 0.2
    input_dropout: 0
    n_regimes: 2
    use_last: true
  pl_model:
    learning_rate: 0.0038
    optimizer_name: adam
    weight_decay: 0.0005
