# @package _global_

model:
  data:
    batch_size: 1024
  model:
    dropout: 0
    input_dropout: 0
    n_regimes: 8
    use_last: true
  pl_model:
    learning_rate: 0.0098
    optimizer_name: adamw
    weight_decay: 0.0001
