# @package _global_

model:
  data:
    batch_size: 256
  model:
    dropout: 0.1
    input_dropout: 0
    n_regimes: 1
    use_last: true
  pl_model:
    learning_rate: 0.0009
    optimizer_name: adamw
    weight_decay: 0
