# @package _global_

model:
  model:
    n_estimators: 770
    max_depth: 4
    reg_alpha: 2.271
    reg_lambda: 5.177
    subsample: 0.824
    colsample_bytree: 0.993
    learning_rate: 0.062