# @package _global_

model:
  model:
    n_estimators: 568
    max_depth: 4
    reg_alpha: 3.495
    reg_lambda: 13.733
    subsample: 0.697
    colsample_bytree: 0.612
    learning_rate: 0.0661