# @package _global_

model:
  model:
    n_estimators: 312
    max_depth: 6
    reg_alpha: 0.0008
    reg_lambda: 1.382
    subsample: 0.9853
    colsample_bytree: 0.788
    learning_rate: 0.0571