# @package _global_

model:
  model:
    n_estimators: 750
    max_depth: 3
    reg_alpha: 0.213
    reg_lambda: 16.316
    subsample: 0.915
    colsample_bytree: 0.879
    learning_rate: 0.01