# @package _global_

look_back_window: 47

model:
  model:
    n_estimators: 507
    max_depth: 5
    reg_alpha: 0.0
    reg_lambda: 7.915
    subsample: 0.7139
    colsample_bytree: 0.892
    learning_rate: 0.0241