# @package _global_

look_back_window: 10
model:
  data:
    batch_size: 64
  model:
    dropout: 0.2
    input_dropout: 0.3
    n_regimes: 32
    use_last: false
  pl_model:
    learning_rate: 0.0004
    optimizer_name: adamw
    weight_decay: 0.0001
