# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.2881
    dropout_prob_theta: 0.1647
    kernel_size: 5
    n_hidden: 100
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.003
    weight_decay: 0.0186
