# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.4088
    dropout_prob_theta: 0.1298
    kernel_size: 4
    n_hidden: 250
    stack_types:
    - identity
    - exogenous_tcn
  pl_model:
    learning_rate: 0.001
    weight_decay: 0.0
