# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.0348
    dropout_prob_theta: 0.19
    kernel_size: 5
    n_hidden: 100
    stack_types:
    - exogenous_tcn
    - identity
  pl_model:
    learning_rate: 0.0011
    weight_decay: 0.0016
