# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.3367
    dropout_prob_theta: 0.197
    kernel_size: 3
    n_hidden: 100
    stack_types:
    - exogenous_wavenet
    - identity
  pl_model:
    learning_rate: 0.006
    weight_decay: 0.0005
