# @package _global_

model:
  model:
    dropout_prob_exogenous: 0.0285
    dropout_prob_theta: 0.2556
    kernel_size: 2
    n_hidden: 500
    stack_types:
    - identity
    - exogenous_wavenet
  pl_model:
    learning_rate: 0.002
    weight_decay: 0.0004
