# @package _global_

look_back_window: 30

model:
  pl_model:
    optimizer_name: "adam"
    learning_rate: 0.0015
    weight_decay: 0.000001
  model:
    n_regimes: 16
    use_last: False 
    dropout: 0.1 
    input_dropout: 0.0
  data:
    batch_size: 256